### ISSUE TITLE
Error with changing config

### ISSUE THREAD

**Issue by Maitlans** [SimpleMC/SimpleHealthbars2#15]
I'm getting an error when I try to change anything having to do with the player health.
https://pastebin.com/5Qmy6978

Also as a side suggestion: Could you please make the plugin Citizens Sentinel compatible? It's a plugin which makes Player like NPCs into enemies but the health will always show as 0 on them. Thank you keep up the awesome work, lots of potential here!

**Comment by tajobe** [comment]
Thanks for the report!

I chose to make `NAME` not a valid type for Players as it would change the name in chat and anywhere else using `displayName` (other plugins, etc), but not the nametag. As far as I know, health bars on the NAME isn't possible within the API and would require NMS/packets. I'll add a more descriptive error and update the README (PR #16).

If you like the styling of a bar rather than hearts, the ACTION healthbar has that as well, but isn't visible to others in the world.


As for the Citizens issue, I'm not super familiar with their API but if they are spawning `LivingEntity`s it should work. That said, there are a few things that could be going wrong. What's your `mob-bar` config? I have a hunch that they are not setting the `GENERIC_MAX_HEALTH` attribute which is how we get the max health. Could you try `ABSOLUTE` style and let me know if it is able to grab the health?

Edited: Better reasoning

**Comment by Maitlans** [comment]
Thank you so much, the issue with the NPCs is that they're considered players so the player bar for health is what appears which shows as 0 not the mob one. 
![image](https://user-images.githubusercontent.com/51733032/74599640-3599c900-5053-11ea-9cca-75d4632f238e.png)

**Comment by Maitlans** [comment]
I think it may be an issue all health plugins always have with Citizens plugin never really seen one that works completely, could you add an option for disabling it for players just so they don't appear on the NPCs? 

Also I have a tiny suggestion for Mythicmobs if you are familiar with their API, so right now when you attack a mythicmobs mob and they don't have their "AlwaysShowName:" set to true and you attack them then their name will be the default name of the mob such as "Skeleton" "Spider" and such, so they basically lose their name but the nice thing about having "AlwaysShowName:" to false is that you don't see the nametags through the walls as well as it's nicer for optimization if you have tons of mobs in an area not having to see their nametags until you are actually attacking them. So would be cool if you integrated your plugin a bit more with Mythicmobs and perhaps you could list it as supported. It's not a big deal if not since it's a tiny detail. 

Thank you so much for the awesome plugin, sorry for the pestering. 😄

**Comment by tajobe** [comment]
> could you add an option for disabling it for players

You can set the `type` to `NONE` on either `mob-bar` or `player-bar` to disable that config. So, if it is picking up the player config you can set:
```yaml
player-bar:
  type: NONE
```

I looked briefly into MythicMobs and it doesn't exactly seem simple to start up, but I can potentially check if they set the custom name (whether it's visible or not). ~Would you mind making a separate issue for showing the correct MythicMobs names with `AlwaysShowName` of `false`~?

**Comment by tajobe** [comment]
I went ahead and created separate issues for the citizens (#17) and MythicMobs (#18) problems. I can't really promise I'll get to them soon though someone else can pick them up. Let me know if that covers it and we can close this issue in favor of tracking them individually.

**Comment by Maitlans** [comment]
Thank you so much, yes disabling it on the NPCs by disabling it on the players worked. Closing.
